services:
  - type: web
    name: todo-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /app
        destination: /app/index.html
      - type: rewrite
        source: /app/*
        destination: /app/index.html
